version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    env_file: ./.env
    container_name: $DB_CONTAINER_NAME
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_LOCAL_PORT
    networks:
      - backend

  api:
    depends_on:
      - mysql
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend

  ui:
    depends_on:
      - api
    build:
      context: ./ui
      dockerfile: ../docker/ui/Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  mysql:

networks:
  backend:
  frontend: